"""Initial migration

Revision ID: 4c45ede6d241
Revises: 
Create Date: 2026-02-11 19:13:04.380423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c45ede6d241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('emission_time', sa.Time(), nullable=False),
    sa.Column('location', sa.Enum('LA_PLATA', 'MAR_DEL_PLATA', 'JUNIN', name='city'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_forecast_date'), ['forecast_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_location'), ['location'], unique=False)

    op.create_table('daily_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('day_name', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('temp_min_apparent', sa.Float(), nullable=True),
    sa.Column('temp_max_apparent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_forecasts_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_forecasts_forecast_id'), ['forecast_id'], unique=False)

    op.create_table('period_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_forecast_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('EARLY_MORNING', 'MORNING', 'AFTERNOON', 'NIGHT', name='timeperiod'), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('sky_condition', sa.Enum('CLEAR', 'PARTLY_CLOUDY', 'SOMEWHAT_CLOUDY', 'CLOUDY', 'OVERCAST', name='skycondition'), nullable=True),
    sa.Column('precipitation_description', sa.String(length=200), nullable=True),
    sa.Column('wind_direction', sa.Enum('NORTH', 'SOUTH', 'EAST', 'WEST', 'NORTHEAST', 'NORTHWEST', 'SOUTHEAST', 'SOUTHWEST', name='winddirection'), nullable=True),
    sa.Column('wind_intensity', sa.Enum('CALM', 'LIGHT', 'MODERATE', 'STRONG', 'VERY_STRONG', name='windintensity'), nullable=True),
    sa.Column('weather_icon_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['daily_forecast_id'], ['daily_forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('period_forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_period_forecasts_daily_forecast_id'), ['daily_forecast_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('period_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_period_forecasts_daily_forecast_id'))

    op.drop_table('period_forecasts')
    with op.batch_alter_table('daily_forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_forecasts_forecast_id'))
        batch_op.drop_index(batch_op.f('ix_daily_forecasts_date'))

    op.drop_table('daily_forecasts')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_location'))
        batch_op.drop_index(batch_op.f('ix_forecasts_forecast_date'))

    op.drop_table('forecasts')
    # ### end Alembic commands ###
